/**
 * YOU V2 — Capability Registry: Widget Catalog
 *
 * Single source of truth describing every widget, signal, and data surface
 * available in the You page. Pure data — no React imports, no side effects —
 * so this module can be loaded server-side (composer prompt building, validator,
 * future public docs) and client-side (template apply, composer rendering).
 *
 * Component → React lazy() bindings live in:
 *   apps/research/src/pages/you/you-component-map.js
 *
 * Schema is documented via JSDoc @typedef in ./index.js.
 *
 * Future migration path: when the trading app needs the same registry, promote
 * this file to packages/registry/widgets.js and import from there.
 */

/** @type {import('./index.js').WidgetEntry[]} */
export const WIDGETS = [
  /* ── METRICS ─────────────────────────────────────────────────── */
  {
    id: 'you-btc-price',
    name: 'BTC Price',
    description: 'Bitcoin live price with 24h change and a 7-day sparkline.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?id=bitcoin', refresh_interval_ms: 30000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'BTC', name: 'Bitcoin', coingeckoId: 'bitcoin' },
    default_size: { w: 3, h: 2 },
    min_size: { w: 2, h: 2 },
    max_size: { w: 4, h: 3 },
    companions: ['you-eth-price', 'you-fear-greed', 'you-chart'],
    use_cases: [
      'Anchor a dashboard with the most-watched price in crypto',
      'Glance check before opening a deeper analysis tool',
    ],
    tags: ['btc', 'bitcoin', 'price', 'sparkline', 'metric'],
  },
  {
    id: 'you-eth-price',
    name: 'ETH Price',
    description: 'Ethereum live price with 24h change and a 7-day sparkline.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?id=ethereum', refresh_interval_ms: 30000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'ETH', name: 'Ethereum', coingeckoId: 'ethereum' },
    default_size: { w: 3, h: 2 },
    min_size: { w: 2, h: 2 },
    max_size: { w: 4, h: 3 },
    companions: ['you-btc-price', 'you-sol-price', 'you-onchain'],
    use_cases: ['Track ETH next to BTC for relative-strength reads'],
    tags: ['eth', 'ethereum', 'price', 'sparkline', 'metric'],
  },
  {
    id: 'you-sol-price',
    name: 'SOL Price',
    description: 'Solana live price with 24h change and a 7-day sparkline.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?id=solana', refresh_interval_ms: 30000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'SOL', name: 'Solana', coingeckoId: 'solana' },
    default_size: { w: 3, h: 2 },
    min_size: { w: 2, h: 2 },
    max_size: { w: 4, h: 3 },
    companions: ['you-btc-price', 'you-eth-price', 'you-discovery'],
    use_cases: ['Watch the dominant alt-L1 alongside majors'],
    tags: ['sol', 'solana', 'price', 'sparkline', 'metric'],
  },
  {
    id: 'you-bnb-price',
    name: 'BNB Price',
    description: 'BNB live price with 24h change and a 7-day sparkline.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?id=binancecoin', refresh_interval_ms: 30000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'BNB', name: 'BNB', coingeckoId: 'binancecoin' },
    default_size: { w: 3, h: 2 },
    min_size: { w: 2, h: 2 },
    max_size: { w: 4, h: 3 },
    companions: ['you-btc-price', 'you-funding-heatmap'],
    use_cases: ['Track exchange-token flow alongside funding data'],
    tags: ['bnb', 'binance', 'price', 'sparkline', 'metric'],
  },
  {
    id: 'you-fear-greed',
    name: 'Fear & Greed',
    description: 'Crypto Fear & Greed Index gauge with 30-day history.',
    category: ['sentiment', 'macro'],
    data_source: { type: 'brain', endpoint: '/brain/fear-greed', refresh_interval_ms: 300000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 3 },
    min_size: { w: 3, h: 2 },
    max_size: { w: 6, h: 4 },
    companions: ['you-macro-signals', 'you-verdict', 'you-heatmap'],
    use_cases: [
      'Calibrate position sizing against the broader sentiment regime',
      'Spot extremes that historically mark turning points',
    ],
    tags: ['sentiment', 'fear-greed', 'gauge', 'cmc', 'macro'],
  },
  {
    id: 'you-liq-summary',
    name: 'Liquidations 24h',
    description: '24h liquidation totals with long/short split and daily bars.',
    category: ['derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/liquidations/summary', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 3 },
    min_size: { w: 3, h: 2 },
    max_size: { w: 6, h: 4 },
    companions: ['you-liq-bars', 'you-liq-bubbles', 'you-funding-heatmap'],
    use_cases: ['Quick read on overnight cascades before opening risk'],
    tags: ['liquidations', 'derivatives', 'risk'],
  },
  {
    id: 'you-open-interest',
    name: 'Open Interest',
    description: 'Aggregate perp OI with 24h change and dominant funding rate.',
    category: ['derivatives', 'perps'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/open-interest', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 3 },
    min_size: { w: 3, h: 2 },
    max_size: { w: 6, h: 4 },
    companions: ['you-funding-heatmap', 'you-cvd', 'you-liq-summary'],
    use_cases: ['Track positioning expansion before squeezes'],
    tags: ['oi', 'open-interest', 'perps', 'derivatives', 'funding'],
  },
  {
    id: 'you-funding-heatmap',
    name: 'Funding Heatmap',
    description: 'Funding rates across top tokens and exchanges.',
    category: ['derivatives', 'perps'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/funding/heatmap', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 6 },
    companions: ['you-open-interest', 'you-cvd', 'you-liq-bubbles'],
    use_cases: [
      'Spot funding asymmetry across venues',
      'Find tokens where the perp curve is leaning hard one way',
    ],
    tags: ['funding', 'heatmap', 'perps', 'derivatives', 'exchanges'],
  },

  /* ── CHARTS ──────────────────────────────────────────────────── */
  {
    id: 'you-chart',
    name: 'TradingView Chart',
    description: 'Full TradingView chart with timeframes, indicators, and drawings.',
    category: ['cex', 'dex'],
    data_source: { type: 'spectre_api', endpoint: '/api/tradingview/udf/history', refresh_interval_ms: 15000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'BTCUSDT' },
    default_size: { w: 8, h: 5 },
    min_size: { w: 6, h: 4 },
    max_size: { w: 12, h: 8 },
    companions: ['you-cvd', 'you-orderbook', 'you-liq-bars'],
    use_cases: ['Primary technical surface for any trading dashboard'],
    tags: ['chart', 'tradingview', 'candles', 'price'],
  },
  {
    id: 'you-liq-bars',
    name: 'Liquidation Bars',
    description: 'Horizontal bars showing liquidation clusters above and below price.',
    category: ['derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/liquidations/levels', refresh_interval_ms: 30000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-chart', 'you-liq-bubbles', 'you-orderbook'],
    use_cases: ['Find magnetic price levels where liquidity stacks'],
    tags: ['liquidations', 'levels', 'derivatives'],
  },
  {
    id: 'you-liq-bubbles',
    name: 'Liquidation Bubbles',
    description: 'Bubble map of liquidation clusters by size and price level.',
    category: ['derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/liquidations/bubbles', refresh_interval_ms: 30000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-liq-bars', 'you-liq-timeline', 'you-funding-heatmap'],
    use_cases: ['Visual scan of where the largest cascades just hit'],
    tags: ['liquidations', 'bubbles', 'derivatives'],
  },
  {
    id: 'you-liq-timeline',
    name: 'Liquidation Timeline',
    description: 'Historical liquidation volume with spike detection.',
    category: ['derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/liquidations/timeline', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 5 },
    companions: ['you-liq-summary', 'you-liq-bars'],
    use_cases: ['Catch repeated cascades before they cluster into a flush'],
    tags: ['liquidations', 'timeline', 'derivatives'],
  },
  {
    id: 'you-cvd',
    name: 'CVD (Volume Delta)',
    description: 'Cumulative volume delta with divergence detection.',
    category: ['derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/cvd', refresh_interval_ms: 15000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-chart', 'you-orderbook', 'you-funding-heatmap'],
    use_cases: ['Sniff hidden buyers/sellers when price stalls'],
    tags: ['cvd', 'volume-delta', 'derivatives', 'orderflow'],
  },
  {
    id: 'you-orderbook',
    name: 'Order Book Depth',
    description: 'Mirrored depth chart with bid/ask ratio and large-order tags.',
    category: ['cex', 'derivatives'],
    data_source: { type: 'external', endpoint: '/api/derivatives/orderbook/depth', refresh_interval_ms: 5000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-chart', 'you-cvd', 'you-liq-bars'],
    use_cases: ['Detect spoof walls and real liquidity ahead of breakouts'],
    tags: ['orderbook', 'depth', 'cex', 'liquidity'],
  },

  /* ── FLOW & ON-CHAIN ─────────────────────────────────────────── */
  {
    id: 'you-exchange-flows',
    name: 'Exchange Flows',
    description: 'Net exchange inflows/outflows with a live event feed.',
    category: ['onchain', 'cex'],
    data_source: { type: 'spectre_api', endpoint: '/api/onchain/exchange-flows', refresh_interval_ms: 60000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-whale-alerts', 'you-onchain', 'you-etf-flows'],
    use_cases: [
      'Watch supply leaving exchanges for accumulation cues',
      'Catch deposit waves that often precede sells',
    ],
    tags: ['exchange-flows', 'onchain', 'cex', 'flows'],
  },
  {
    id: 'you-etf-flows',
    name: 'ETF Flows',
    description: 'BTC spot ETF daily flows — IBIT, FBTC, GBTC, and the rest.',
    category: ['macro', 'portfolio', 'rwa'],
    data_source: { type: 'spectre_api', endpoint: '/api/etf/flows', refresh_interval_ms: 3600000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 5 },
    companions: ['you-btc-price', 'you-exchange-flows', 'you-macro-signals'],
    use_cases: ['Read institutional appetite at the source'],
    tags: ['etf', 'btc', 'institutional', 'flows', 'macro'],
  },
  {
    id: 'you-whale-alerts',
    name: 'Whale Alerts',
    description: 'Live whale transaction feed with chain badges and USD sizing.',
    category: ['onchain', 'whale'],
    data_source: { type: 'brain', endpoint: '/brain/whale-flows', refresh_interval_ms: 30000 },
    tier: 1000,
    required_props: {},
    default_props: { min_usd_value: 100000, lookback_hours: 24 },
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-exchange-flows', 'you-onchain', 'you-discovery'],
    use_cases: [
      'Track institutional accumulation in real time',
      'Spot distribution before retail catches on',
    ],
    tags: ['whales', 'smart-money', 'flows', 'institutional', 'onchain'],
  },
  {
    id: 'you-onchain',
    name: 'On-Chain Metrics',
    description: 'Active addresses, exchange reserves, HODL waves, MVRV.',
    category: ['onchain'],
    data_source: { type: 'brain', endpoint: '/brain/onchain-metrics', refresh_interval_ms: 600000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-exchange-flows', 'you-whale-alerts', 'you-verdict'],
    use_cases: ['Confirm price moves with structural on-chain context'],
    tags: ['onchain', 'metrics', 'mvrv', 'addresses', 'reserves'],
  },

  /* ── INTELLIGENCE ────────────────────────────────────────────── */
  {
    id: 'you-ai-brief',
    name: 'AI Brief',
    description: 'One-paragraph market summary from Spectre AI.',
    category: ['agent', 'brain'],
    data_source: { type: 'brain', endpoint: '/brain/brief', refresh_interval_ms: 600000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 4 },
    companions: ['you-verdict', 'you-fear-greed', 'you-news-feed'],
    use_cases: ['Open the day with a synthesized read instead of a chart wall'],
    tags: ['ai', 'brief', 'brain', 'summary', 'agent'],
  },
  {
    id: 'you-verdict',
    name: 'Spectre Verdict',
    description: 'Market stance with signal-by-signal breakdown.',
    category: ['agent', 'brain'],
    data_source: { type: 'brain', endpoint: '/brain/verdict', refresh_interval_ms: 600000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-ai-brief', 'you-ghost', 'you-screener'],
    use_cases: ['Pressure-test your bias against the platform consensus'],
    tags: ['verdict', 'brain', 'agent', 'signals'],
  },
  {
    id: 'you-ghost',
    name: 'Ghost Mode',
    description: 'Counter-thesis risk briefing with watch alerts.',
    category: ['agent', 'sentiment'],
    data_source: { type: 'consciousness', endpoint: '/consciousness/ghost', refresh_interval_ms: 600000 },
    tier: 7000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-verdict', 'you-macro-signals', 'you-narrative-tracker'],
    use_cases: ['Force a steel-man of the bear case before sizing up'],
    tags: ['ghost', 'consciousness', 'agent', 'risk', 'counter-thesis'],
  },
  {
    id: 'you-screener',
    name: 'AI Screener',
    description: 'Token signal table — accumulate, watch, or avoid.',
    category: ['agent', 'brain'],
    data_source: { type: 'brain', endpoint: '/brain/screener', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 8, h: 5 },
    min_size: { w: 6, h: 4 },
    max_size: { w: 12, h: 8 },
    companions: ['you-discovery', 'you-narrative-tracker', 'you-watchlist'],
    use_cases: [
      'Triage a long token list into a manageable shortlist',
      'Find names other dashboards miss',
    ],
    tags: ['screener', 'brain', 'agent', 'signals', 'tokens'],
  },

  /* ── PORTFOLIO ───────────────────────────────────────────────── */
  {
    id: 'you-watchlist',
    name: 'Watchlist',
    description: 'Your tracked tokens with sparklines and 24h change.',
    category: ['portfolio'],
    data_source: { type: 'spectre_api', endpoint: '/api/watchlists', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 5 },
    min_size: { w: 3, h: 4 },
    max_size: { w: 6, h: 8 },
    companions: ['you-screener', 'you-discovery', 'you-positions'],
    use_cases: ['Keep your shortlist visible while you scan the rest of the dashboard'],
    tags: ['watchlist', 'portfolio', 'tokens'],
  },
  {
    id: 'you-positions',
    name: 'Positions',
    description: 'Active trades with P&L, leverage, entry, and current price.',
    category: ['portfolio'],
    data_source: { type: 'spectre_api', endpoint: '/api/positions', refresh_interval_ms: 15000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 6 },
    companions: ['you-portfolio-ring', 'you-alerts', 'you-watchlist'],
    use_cases: ['See live exposure without leaving the dashboard'],
    tags: ['positions', 'portfolio', 'pnl', 'leverage'],
  },
  {
    id: 'you-portfolio-ring',
    name: 'Portfolio Ring',
    description: 'Donut chart of portfolio allocation by asset.',
    category: ['portfolio'],
    data_source: { type: 'spectre_api', endpoint: '/api/portfolio/allocation', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-positions', 'you-watchlist'],
    use_cases: ['Spot concentration risk at a glance'],
    tags: ['portfolio', 'allocation', 'donut', 'ring'],
  },
  {
    id: 'you-alerts',
    name: 'Active Alerts',
    description: 'Price alerts with status — watching, triggered, resolved.',
    category: ['portfolio', 'agent'],
    data_source: { type: 'spectre_api', endpoint: '/api/alerts', refresh_interval_ms: 30000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-watchlist', 'you-positions'],
    use_cases: ['Park your trade plan where you can see it'],
    tags: ['alerts', 'portfolio', 'price-alerts'],
  },

  /* ── YOU EXCLUSIVES ──────────────────────────────────────────── */
  {
    id: 'you-news-feed',
    name: 'News Feed',
    description: 'Latest crypto and macro news with sentiment scoring.',
    category: ['social', 'narrative', 'macro', 'rwa'],
    data_source: { type: 'spectre_api', endpoint: '/api/news', refresh_interval_ms: 120000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-crypto-twitter', 'you-narrative-tracker', 'you-economic-calendar'],
    use_cases: ['Stay current without leaving the dashboard'],
    tags: ['news', 'social', 'narrative', 'sentiment'],
  },
  {
    id: 'you-economic-calendar',
    name: 'Economic Calendar',
    description: 'Key macro events with impact levels and timing.',
    category: ['macro', 'rwa'],
    data_source: { type: 'spectre_api', endpoint: '/api/calendar', refresh_interval_ms: 1800000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-macro-signals', 'you-news-feed', 'you-fear-greed'],
    use_cases: ['Avoid getting caught flat-footed on CPI or FOMC'],
    tags: ['calendar', 'macro', 'events', 'fomc', 'cpi'],
  },
  {
    id: 'you-narrative-tracker',
    name: 'Narrative Tracker',
    description: 'Sector lifecycle stages — Early to Exhausted — with mindshare deltas.',
    category: ['narrative', 'social', 'rwa'],
    data_source: { type: 'brain', endpoint: '/brain/narratives', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-screener', 'you-discovery', 'you-crypto-twitter'],
    use_cases: ['Catch narratives before they peak, exit before they exhaust'],
    tags: ['narrative', 'sectors', 'lifecycle', 'mindshare'],
  },
  {
    id: 'you-macro-signals',
    name: 'Macro Signals',
    description: 'AI-derived market bias, volatility regime, and positioning.',
    category: ['macro', 'agent'],
    data_source: { type: 'brain', endpoint: '/brain/macro-signals', refresh_interval_ms: 600000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-fear-greed', 'you-economic-calendar', 'you-verdict'],
    use_cases: ['Anchor risk management on the macro regime, not the candle'],
    tags: ['macro', 'signals', 'bias', 'volatility', 'agent'],
  },
  {
    id: 'you-roi-calculator',
    name: 'ROI Calculator',
    description: 'Current price vs ATH — what could your investment return?',
    category: ['portfolio'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: { coingeckoId: 'bitcoin', amount_usd: 1000 },
    default_size: { w: 4, h: 3 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 4 },
    companions: ['you-watchlist', 'you-discovery'],
    use_cases: ['Quickly model upside if a token returns to ATH'],
    tags: ['roi', 'calculator', 'portfolio', 'ath'],
  },
  {
    id: 'you-market-flows',
    name: 'Market Flows',
    description: 'Funding, liquidations, and whale flows at a glance.',
    category: ['derivatives', 'onchain'],
    data_source: { type: 'spectre_api', endpoint: '/api/market-flows', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 5 },
    companions: ['you-funding-heatmap', 'you-whale-alerts', 'you-liq-summary'],
    use_cases: ['One panel that bundles three signals you check together anyway'],
    tags: ['flows', 'derivatives', 'onchain', 'composite'],
  },
  {
    id: 'you-discovery',
    name: 'Discovery',
    description: 'Trending tokens and top gainers with performance.',
    category: ['dex', 'narrative'],
    data_source: { type: 'spectre_api', endpoint: '/api/trending', refresh_interval_ms: 120000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-narrative-tracker', 'you-screener', 'you-crypto-twitter'],
    use_cases: ['Surface what is actually moving today, not yesterday'],
    tags: ['discovery', 'trending', 'gainers', 'dex'],
  },
  {
    id: 'you-crypto-twitter',
    name: 'Crypto X',
    description: 'Crypto Twitter pulse — trending posts and influential takes.',
    category: ['social', 'sentiment'],
    data_source: { type: 'spectre_api', endpoint: '/api/social/cryptotwitter', refresh_interval_ms: 180000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 5 },
    min_size: { w: 3, h: 4 },
    max_size: { w: 6, h: 8 },
    companions: ['you-news-feed', 'you-narrative-tracker', 'you-discovery'],
    use_cases: ['Watch the crowd without doom-scrolling X'],
    tags: ['twitter', 'x', 'social', 'sentiment'],
  },
  {
    id: 'you-top-coins',
    name: 'Top Coins',
    description: 'Top 10 by market cap with live prices and changes.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?action=top10', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: { limit: 10 },
    default_size: { w: 4, h: 5 },
    min_size: { w: 3, h: 4 },
    max_size: { w: 6, h: 8 },
    companions: ['you-heatmap', 'you-watchlist'],
    use_cases: ['Anchor any dashboard with the macro leaders'],
    tags: ['top-coins', 'market-cap', 'leaders'],
  },
  {
    id: 'you-heatmap',
    name: 'Market Heatmap',
    description: 'Top 30 coins as a treemap colored by 24h performance.',
    category: ['cex', 'sentiment'],
    data_source: { type: 'external', endpoint: '/api/cg-proxy?action=top30', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 8, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 6 },
    companions: ['you-top-coins', 'you-fear-greed'],
    use_cases: ['Visual scan of what is leading and lagging today'],
    tags: ['heatmap', 'treemap', 'performance'],
  },

  {
    id: 'you-rwa-overview',
    name: 'RWA Overview',
    description: 'Real-world asset TVL, top protocols, and 24h movers from /api/rwa.',
    category: ['rwa', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/rwa/overview', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 6 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-news-feed', 'you-narrative-tracker', 'you-etf-flows', 'you-economic-calendar'],
    use_cases: [
      'Track tokenized real-world assets — gold, T-bills, private credit',
      'Spot which RWA protocols are absorbing fresh institutional flow',
    ],
    tags: ['rwa', 'tokenized-assets', 'tvl', 'institutional', 'gold', 'treasuries'],
  },

  {
    id: 'you-stock-movers',
    name: 'Stock Movers',
    description: 'Top US equity gainers and losers — for traders watching crypto-equity correlation.',
    category: ['macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/stocks/movers', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-us-market', 'you-economic-calendar', 'you-etf-flows'],
    use_cases: ['Watch equity rotations alongside crypto', 'Spot risk-on/risk-off signals from US markets'],
    tags: ['stocks', 'equities', 'movers', 'us-markets', 'macro'],
  },
  {
    id: 'you-ai-answer',
    name: 'Ask Spectre',
    description: 'Inline AI question box — quick lookups without leaving the dashboard.',
    category: ['agent', 'brain'],
    data_source: { type: 'spectre_api', endpoint: '/api/monarch/chat', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 12, h: 8 },
    companions: ['you-token-search', 'you-ai-brief', 'you-verdict'],
    use_cases: ['Ask a question without opening a separate chat', 'Quick second opinion on a thesis'],
    tags: ['ai', 'ask', 'agent', 'lookup', 'q-and-a'],
  },
  {
    id: 'you-us-market',
    name: 'US Indices',
    description: 'S&P 500, Nasdaq, Dow Jones, Russell 2000 — live levels and 24h change.',
    category: ['macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/stocks/indices', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-stock-movers', 'you-economic-calendar', 'you-macro-signals'],
    use_cases: ['Read US market regime alongside crypto', 'Calibrate risk-on/off bias'],
    tags: ['indices', 'spx', 'nasdaq', 'dow', 'russell', 'macro'],
  },
  {
    id: 'you-sector-rotation',
    name: 'Sector Rotation',
    description: 'Crypto sectors leaderboard — leaders and laggards by 24h performance.',
    category: ['narrative'],
    data_source: { type: 'spectre_api', endpoint: '/api/market/sectors', refresh_interval_ms: 300000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-narrative-tracker', 'you-mindshare-radar', 'you-screener'],
    use_cases: ['Spot which sectors are absorbing capital today', 'Catch rotation early before mainstream'],
    tags: ['sectors', 'rotation', 'narrative', 'leaders', 'laggards'],
  },
  {
    id: 'you-top-gainers',
    name: 'Top Movers',
    description: 'Top crypto gainers and losers in the last 24h, ranked by percent change.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: '/api/coingecko/coins/markets', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-discovery', 'you-heatmap', 'you-screener'],
    use_cases: ['Find what is moving most today', 'Trade momentum off the leaderboard'],
    tags: ['gainers', 'losers', 'movers', 'momentum'],
  },
  {
    id: 'you-macro-pulse',
    name: 'Macro Pulse',
    description: 'Total crypto market cap, BTC dominance, ETH dominance — the regime in three numbers.',
    category: ['macro', 'sentiment'],
    data_source: { type: 'external', endpoint: '/api/coingecko/global', refresh_interval_ms: 120000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 2 },
    max_size: { w: 12, h: 4 },
    companions: ['you-fear-greed', 'you-us-market', 'you-heatmap'],
    use_cases: ['Read crypto regime at a glance', 'Spot dominance shifts that signal alt season'],
    tags: ['mcap', 'dominance', 'regime', 'macro'],
  },
  {
    id: 'you-token-search',
    name: 'Whisper Search',
    description: 'Natural-language token search powered by Spectre AI — type intent, get tokens.',
    category: ['agent', 'dex', 'cex'],
    data_source: { type: 'spectre_api', endpoint: '/api/search/whisper', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 8 },
    companions: ['you-ai-answer', 'you-discovery', 'you-screener'],
    use_cases: ['Find tokens by description not symbol', 'Pull up a token without remembering its name'],
    tags: ['search', 'whisper', 'lookup', 'ai'],
  },

  {
    id: 'you-rwa-stablecoins',
    name: 'RWA Stablecoins',
    description: 'Tokenized stablecoins breakdown by issuer with TVL and 24h delta.',
    category: ['rwa'],
    data_source: { type: 'spectre_api', endpoint: '/api/rwa/stablecoins', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-rwa-overview', 'you-rwa-chains', 'you-etf-flows'],
    use_cases: ['Track stablecoin issuer dominance', 'Spot stable mint/burn shifts'],
    tags: ['rwa', 'stablecoins', 'usdc', 'usdt', 'tokenized'],
  },
  {
    id: 'you-rwa-chains',
    name: 'RWA Chains',
    description: 'Real-world asset TVL by blockchain — Ethereum, Polygon, Avalanche, Stellar.',
    category: ['rwa', 'onchain'],
    data_source: { type: 'spectre_api', endpoint: '/api/rwa/chains', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-rwa-overview', 'you-rwa-stablecoins'],
    use_cases: ['See which chains institutional capital prefers', 'Spot RWA chain rotation'],
    tags: ['rwa', 'chains', 'tvl', 'ethereum', 'polygon'],
  },
  {
    id: 'you-x-trending',
    name: 'X Trending',
    description: 'Top tokens ranked by X/Twitter mentions over 24h with delta direction.',
    category: ['social', 'sentiment', 'narrative'],
    data_source: { type: 'spectre_api', endpoint: '/api/x-dash/trending', refresh_interval_ms: 180000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 5 },
    min_size: { w: 3, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-crypto-twitter', 'you-narrative-tracker', 'you-mindshare-radar'],
    use_cases: ['Catch tokens before they trend on X', 'Read social momentum via mentions'],
    tags: ['x', 'twitter', 'social', 'mentions', 'trending'],
  },
  {
    id: 'you-token-dossier',
    name: 'Token Dossier',
    description: 'Spectre Dossier — identity, market, safety flags for any token by chain + address.',
    category: ['onchain', 'agent'],
    data_source: { type: 'spectre_api', endpoint: '/api/dossier', refresh_interval_ms: 60000 },
    tier: 500,
    required_props: { chain: 'string', ca: 'string' },
    default_props: { chain: 'eth', ca: '' },
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-chart', 'you-orderbook', 'you-whale-alerts'],
    use_cases: ['Pull a full safety + market read on any token instantly', 'Vet new pairs before sizing'],
    tags: ['dossier', 'token', 'safety', 'identity'],
  },
  {
    id: 'you-crypto-news',
    name: 'Crypto News',
    description: 'Crypto-focused news feed with sentiment dots and source badges.',
    category: ['social', 'narrative'],
    data_source: { type: 'spectre_api', endpoint: '/api/news', refresh_interval_ms: 120000 },
    tier: 0,
    required_props: {},
    default_props: { category: 'crypto' },
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-x-trending', 'you-narrative-tracker', 'you-economic-calendar'],
    use_cases: ['Read-the-room without doom-scrolling', 'Catch sentiment shifts via headlines'],
    tags: ['news', 'sentiment', 'crypto'],
  },

  /* ── MACRO + DATA ────────────────────────────────────────────── */
  {
    id: 'you-fear-greed-history',
    name: 'Fear & Greed History',
    description: 'Historical Fear & Greed Index with 30D / 90D / 1Y line view.',
    category: ['sentiment', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/fear-greed/historical', refresh_interval_ms: 300000 },
    tier: 0,
    required_props: {},
    default_props: { range: 30 },
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-fear-greed', 'you-macro-pulse', 'you-macro-signals'],
    use_cases: [
      'See how today\'s sentiment compares to last quarter',
      'Time accumulation around prior fear extremes',
    ],
    tags: ['fear-greed', 'sentiment', 'history', 'chart'],
  },
  {
    id: 'you-ventures',
    name: 'Ventures',
    description: 'Recent crypto + AI venture funding rounds with size, sector, and source.',
    category: ['narrative', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/private/funding-news', refresh_interval_ms: 600000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-llama-raises', 'you-accelerators', 'you-narrative-tracker'],
    use_cases: [
      'Track which sectors VCs are funding right now',
      'Catch new protocols before token-launch hype',
    ],
    tags: ['ventures', 'vc', 'funding', 'raises', 'private'],
  },
  {
    id: 'you-llama-raises',
    name: 'Crypto Raises',
    description: 'On-chain protocol fundraising rounds via DefiLlama with leads and valuations.',
    category: ['narrative', 'macro', 'onchain'],
    data_source: { type: 'spectre_api', endpoint: '/api/private/llama-raises', refresh_interval_ms: 900000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-ventures', 'you-narrative-tracker', 'you-discovery'],
    use_cases: [
      'See which protocols just closed rounds before tokens unlock',
      'Map money flow into emerging crypto categories',
    ],
    tags: ['raises', 'defillama', 'protocol', 'crypto-vc'],
  },
  {
    id: 'you-accelerators',
    name: 'Accelerators',
    description: 'New companies from YC + Hub71 cohorts with one-liners and websites.',
    category: ['narrative', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/accelerators/all', refresh_interval_ms: 1800000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-ventures', 'you-llama-raises', 'you-narrative-tracker'],
    use_cases: [
      'Spot Web3 / AI startups before they raise institutional rounds',
      'Watch the YC + Hub71 pipeline for new builders',
    ],
    tags: ['accelerator', 'yc', 'hub71', 'startups'],
  },
  {
    id: 'you-sec-filings',
    name: 'SEC Filings',
    description: 'Recent SEC filings — 13F, D, 8-K — with form type tone and entity.',
    category: ['macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/private/sec-filings', refresh_interval_ms: 900000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-ventures', 'you-economic-calendar', 'you-news-feed'],
    use_cases: [
      'Catch institutional crypto exposure before it hits headlines',
      'Watch insider activity in public crypto-adjacent companies',
    ],
    tags: ['sec', 'filings', 'institutional', 'compliance'],
  },
  {
    id: 'you-liq-heatmap',
    name: 'Liq Heatmap',
    description: 'Top liquidation cluster levels for BTC / ETH / SOL with above/below tone.',
    category: ['perps', 'derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/charts/liq-heatmap', refresh_interval_ms: 300000 },
    tier: 0,
    required_props: {},
    default_props: { symbol: 'BTCUSDT' },
    default_size: { w: 4, h: 5 },
    min_size: { w: 3, h: 4 },
    max_size: { w: 6, h: 8 },
    companions: ['you-liq-summary', 'you-liq-bubbles', 'you-funding-heatmap'],
    use_cases: [
      'Spot the next big liq magnet above and below price',
      'Frame stop-loss placement around real liquidation density',
    ],
    tags: ['liquidations', 'heatmap', 'levels', 'perps'],
  },
  {
    id: 'you-tradingview-mini',
    name: 'Mini Chart',
    description: 'TradingView mini chart for the selected token with 1D/1M/3M/1Y ranges.',
    category: ['cex'],
    data_source: { type: 'external', endpoint: 'https://www.tradingview.com/embed', refresh_interval_ms: 60000 },
    tier: 0,
    required_props: {},
    default_props: { range: '1M' },
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-token-dossier', 'you-btc-price', 'you-chart'],
    use_cases: ['Glance at price action for the token in focus without context-switching'],
    tags: ['chart', 'tradingview', 'price', 'mini'],
  },
  {
    id: 'you-unicorns',
    name: 'Unicorns',
    description: 'Private market unicorns ranked by valuation, filterable by sector.',
    category: ['narrative', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/private/unicorns', refresh_interval_ms: 3600000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 10 },
    companions: ['you-ventures', 'you-llama-raises', 'you-vc-sector-heat'],
    use_cases: [
      'Track AI / fintech / Web3 giants alongside crypto markets',
      'See which sectors host the most decacorns + hectocorns',
    ],
    tags: ['unicorns', 'private', 'valuation', 'startups'],
  },
  {
    id: 'you-earnings',
    name: 'Earnings Calendar',
    description: 'Upcoming US equity earnings with crypto-adjacent tickers highlighted (COIN, MSTR, NVDA…).',
    category: ['macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/stocks/earnings-calendar', refresh_interval_ms: 1800000 },
    tier: 0,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 8 },
    companions: ['you-economic-calendar', 'you-us-market', 'you-stock-movers'],
    use_cases: [
      'Anticipate risk-on flows from NVDA / TSLA prints',
      'Know exactly when COIN / MSTR / mining names report',
    ],
    tags: ['earnings', 'stocks', 'macro', 'calendar'],
  },
  {
    id: 'you-vc-sector-heat',
    name: 'VC Sector Heat',
    description: 'Capital deployed by sector over the last 30D — where venture money is actually flowing.',
    category: ['narrative', 'macro'],
    data_source: { type: 'spectre_api', endpoint: '/api/private/sector-heatmap', refresh_interval_ms: 1800000 },
    tier: 500,
    required_props: {},
    default_props: {},
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 8, h: 8 },
    companions: ['you-ventures', 'you-llama-raises', 'you-unicorns'],
    use_cases: [
      'Confirm whether AI / Web3 hype maps to actual VC dollars',
      'See sector rotation in private markets before it shows up on-chain',
    ],
    tags: ['vc', 'sector', 'heatmap', 'deployment', 'private'],
  },

  /* ── PLANNED (status: planned — not built today) ─────────────── */
  {
    id: 'you-perp-funding-skew',
    name: 'Perp Funding Skew',
    description: 'Funding skew across exchanges with short-side / long-side bias.',
    category: ['perps', 'derivatives'],
    data_source: { type: 'spectre_api', endpoint: '/api/derivatives/funding/skew', refresh_interval_ms: 60000 },
    tier: 1000,
    required_props: {},
    default_props: {},
    default_size: { w: 6, h: 3 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 5 },
    companions: ['you-funding-heatmap', 'you-cvd', 'you-open-interest'],
    use_cases: [
      'Spot squeeze setups where one side is paying through the nose',
      'Validate breakout direction with funding posture',
    ],
    tags: ['funding', 'skew', 'perps', 'derivatives'],
  },
  {
    id: 'you-smart-money-trader',
    name: 'Smart Money Leaderboard',
    description: 'Top performing wallets ranked by realized PnL on tokens you watch.',
    category: ['onchain', 'whale'],
    data_source: { type: 'brain', endpoint: '/brain/smart-money', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: { lookback_days: 30 },
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-whale-alerts', 'you-exchange-flows', 'you-discovery'],
    use_cases: [
      'Follow proven wallets, not anonymous noise',
      'Surface accumulation by historically-correct addresses',
    ],
    tags: ['smart-money', 'wallets', 'leaderboard', 'onchain', 'planned'],
    status: 'planned',
  },
  {
    id: 'you-dex-new-pairs',
    name: 'New DEX Pairs',
    description: 'Freshly listed DEX pairs with GoPlus safety scores and early liquidity.',
    category: ['dex', 'onchain'],
    data_source: { type: 'spectre_api', endpoint: '/api/dex/new-pairs', refresh_interval_ms: 60000 },
    tier: 1000,
    required_props: {},
    default_props: { min_liquidity_usd: 25000 },
    default_size: { w: 6, h: 5 },
    min_size: { w: 4, h: 4 },
    max_size: { w: 8, h: 8 },
    companions: ['you-discovery', 'you-narrative-tracker', 'you-smart-money-trader'],
    use_cases: ['Hunt new launches without copy-pasting addresses into five tools'],
    tags: ['dex', 'new-pairs', 'launches', 'dexscreener'],
  },
  {
    id: 'you-prediction-markets',
    name: 'Prediction Markets',
    description: 'Polymarket and Kalshi event odds with crypto-relevant filtering.',
    category: ['macro', 'sentiment'],
    data_source: { type: 'spectre_api', endpoint: '/api/predictions', refresh_interval_ms: 300000 },
    tier: 500,
    required_props: {},
    default_props: { category: 'crypto' },
    default_size: { w: 6, h: 4 },
    min_size: { w: 4, h: 3 },
    max_size: { w: 8, h: 6 },
    companions: ['you-economic-calendar', 'you-news-feed', 'you-macro-signals'],
    use_cases: ['Read the crowd-priced probability instead of the loudest pundit'],
    tags: ['prediction', 'polymarket', 'kalshi', 'odds'],
  },
  {
    id: 'you-mindshare-radar',
    name: 'Mindshare Radar',
    description: 'Asset mindshare percent — share of crypto mentions over 24h.',
    category: ['social', 'narrative'],
    data_source: { type: 'brain', endpoint: '/brain/mindshare', refresh_interval_ms: 300000 },
    tier: 1000,
    required_props: {},
    default_props: { window_hours: 24 },
    default_size: { w: 4, h: 4 },
    min_size: { w: 3, h: 3 },
    max_size: { w: 6, h: 6 },
    companions: ['you-narrative-tracker', 'you-crypto-twitter', 'you-discovery'],
    use_cases: ['Quantify attention before price reflects it'],
    tags: ['mindshare', 'attention', 'social', 'narrative'],
  },
];

export default WIDGETS;
