export const CURRENCIES = {
  USD: { code: 'USD', symbol: '$', locale: 'en-US', name: 'US Dollar', flag: '\u{1F1FA}\u{1F1F8}' },
  EUR: { code: 'EUR', symbol: '\u20AC', locale: 'de-DE', name: 'Euro', flag: '\u{1F1EA}\u{1F1FA}' },
  GBP: { code: 'GBP', symbol: '\u00A3', locale: 'en-GB', name: 'British Pound', flag: '\u{1F1EC}\u{1F1E7}' },
  JPY: { code: 'JPY', symbol: '\u00A5', locale: 'ja-JP', name: 'Japanese Yen', flag: '\u{1F1EF}\u{1F1F5}', decimals: 0 },
  CAD: { code: 'CAD', symbol: 'C$', locale: 'en-CA', name: 'Canadian Dollar', flag: '\u{1F1E8}\u{1F1E6}' },
  AUD: { code: 'AUD', symbol: 'A$', locale: 'en-AU', name: 'Australian Dollar', flag: '\u{1F1E6}\u{1F1FA}' },
  CHF: { code: 'CHF', symbol: 'CHF', locale: 'de-CH', name: 'Swiss Franc', flag: '\u{1F1E8}\u{1F1ED}' },
  CNY: { code: 'CNY', symbol: '\u00A5', locale: 'zh-CN', name: 'Chinese Yuan', flag: '\u{1F1E8}\u{1F1F3}' },
  INR: { code: 'INR', symbol: '\u20B9', locale: 'en-IN', name: 'Indian Rupee', flag: '\u{1F1EE}\u{1F1F3}' },
  BRL: { code: 'BRL', symbol: 'R$', locale: 'pt-BR', name: 'Brazilian Real', flag: '\u{1F1E7}\u{1F1F7}' },
  KRW: { code: 'KRW', symbol: '\u20A9', locale: 'ko-KR', name: 'South Korean Won', flag: '\u{1F1F0}\u{1F1F7}', decimals: 0 },
  RUB: { code: 'RUB', symbol: '\u20BD', locale: 'ru-RU', name: 'Russian Ruble', flag: '\u{1F1F7}\u{1F1FA}' },
  TRY: { code: 'TRY', symbol: '\u20BA', locale: 'tr-TR', name: 'Turkish Lira', flag: '\u{1F1F9}\u{1F1F7}' },
  PLN: { code: 'PLN', symbol: 'z\u0142', locale: 'pl-PL', name: 'Polish Zloty', flag: '\u{1F1F5}\u{1F1F1}' },
  UAH: { code: 'UAH', symbol: '\u20B4', locale: 'uk-UA', name: 'Ukrainian Hryvnia', flag: '\u{1F1FA}\u{1F1E6}' },
  IDR: { code: 'IDR', symbol: 'Rp', locale: 'id-ID', name: 'Indonesian Rupiah', flag: '\u{1F1EE}\u{1F1E9}', decimals: 0 },
  VND: { code: 'VND', symbol: '\u20AB', locale: 'vi-VN', name: 'Vietnamese Dong', flag: '\u{1F1FB}\u{1F1F3}', decimals: 0 },
  THB: { code: 'THB', symbol: 'THB\u00A0', locale: 'th-TH', name: 'Thai Baht', flag: '\u{1F1F9}\u{1F1ED}' },
  PHP: { code: 'PHP', symbol: '\u20B1', locale: 'en-PH', name: 'Philippine Peso', flag: '\u{1F1F5}\u{1F1ED}' },
  MXN: { code: 'MXN', symbol: 'Mex$', locale: 'es-MX', name: 'Mexican Peso', flag: '\u{1F1F2}\u{1F1FD}' },
  AED: { code: 'AED', symbol: 'AED\u00A0', locale: 'en-AE', name: 'UAE Dirham', flag: '\u{1F1E6}\u{1F1EA}' },
}

export const LANGUAGES = {
  en: { code: 'en', name: 'English', nativeName: 'English', flag: '\u{1F1EC}\u{1F1E7}', dir: 'ltr' },
  fr: { code: 'fr', name: 'French', nativeName: 'Fran\u00E7ais', flag: '\u{1F1EB}\u{1F1F7}', dir: 'ltr' },
  es: { code: 'es', name: 'Spanish', nativeName: 'Espa\u00F1ol', flag: '\u{1F1EA}\u{1F1F8}', dir: 'ltr' },
  zh: { code: 'zh', name: 'Chinese', nativeName: '\u4E2D\u6587', flag: '\u{1F1E8}\u{1F1F3}', dir: 'ltr' },
  hi: { code: 'hi', name: 'Hindi', nativeName: '\u0939\u093F\u0928\u094D\u0926\u0940', flag: '\u{1F1EE}\u{1F1F3}', dir: 'ltr' },
  ar: { code: 'ar', name: 'Arabic', nativeName: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629', flag: '\u{1F1F8}\u{1F1E6}', dir: 'rtl' },
  ru: { code: 'ru', name: 'Russian', nativeName: '\u0420\u0443\u0441\u0441\u043A\u0438\u0439', flag: '\u{1F1F7}\u{1F1FA}', dir: 'ltr' },
  pt: { code: 'pt', name: 'Portuguese', nativeName: 'Portugu\u00EAs', flag: '\u{1F1E7}\u{1F1F7}', dir: 'ltr' },
  nl: { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '\u{1F1F3}\u{1F1F1}', dir: 'ltr' },
  ko: { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '\u{1F1F0}\u{1F1F7}', dir: 'ltr' },
  ja: { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '\u{1F1EF}\u{1F1F5}', dir: 'ltr' },
  vi: { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '\u{1F1FB}\u{1F1F3}', dir: 'ltr' },
  id: { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '\u{1F1EE}\u{1F1E9}', dir: 'ltr' },
  de: { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '\u{1F1E9}\u{1F1EA}', dir: 'ltr' },
  tl: { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '\u{1F1F5}\u{1F1ED}', dir: 'ltr' },
  th: { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '\u{1F1F9}\u{1F1ED}', dir: 'ltr' },
  pl: { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '\u{1F1F5}\u{1F1F1}', dir: 'ltr' },
  tr: { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '\u{1F1F9}\u{1F1F7}', dir: 'ltr' },
  uk: { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '\u{1F1FA}\u{1F1E6}', dir: 'ltr' },
  it: { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '\u{1F1EE}\u{1F1F9}', dir: 'ltr' },
}

export const CURRENCY_LIST = Object.values(CURRENCIES)
export const LANGUAGE_LIST = Object.values(LANGUAGES)
