/**
 * Spectre Intelligence Hub — Content Store
 * JSON file-based storage for articles generated by AI agents.
 */
const fs = require('fs');
const path = require('path');

const ARTICLES_DIR = path.join(__dirname, 'articles');
const BASE_URL = process.env.BASE_URL || 'http://localhost:3001';

// ── IN-MEMORY CACHE ──
// Cache articles per type to avoid re-reading 100+ JSON files on every request.
// Invalidated after CACHE_TTL ms or when saveArticle/deleteArticle is called.
const CACHE_TTL = 15_000; // 15 seconds
const _cache = {}; // { [type]: { articles: [], updatedAt: number } }

function getCachedArticles(type) {
  const entry = _cache[type];
  if (entry && Date.now() - entry.updatedAt < CACHE_TTL) return entry.articles;
  return null;
}

function setCachedArticles(type, articles) {
  _cache[type] = { articles, updatedAt: Date.now() };
}

function invalidateCache(type) {
  if (type) {
    delete _cache[type];
  } else {
    Object.keys(_cache).forEach(k => delete _cache[k]);
  }
}

// Ensure directories exist
['daily', 'crypto', 'stocks', 'research', 'news', 'calendar'].forEach(type => {
  const dir = path.join(ARTICLES_DIR, type);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

/**
 * Save an article to disk.
 * @param {object} article - Full article object
 */
function saveArticle(article) {
  if (!article || !article.type || !article.slug) {
    throw new Error('Article must have type and slug');
  }
  const dir = path.join(ARTICLES_DIR, article.type);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  // Set canonical URL and defaults
  article.canonicalUrl = article.canonicalUrl || `${BASE_URL}/intelligence/${article.type}/${article.slug}`;
  article.ogImage = `${BASE_URL}/og/${article.type}/${article.slug}.png`;
  article.updatedAt = new Date().toISOString();
  if (!article.publishedAt) article.publishedAt = article.updatedAt;
  if (!article.status) article.status = 'published';
  if (!article.version) article.version = 1;

  // Build JSON-LD
  article.jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title || article.headline,
    description: article.summary || '',
    image: article.ogImage,
    author: { '@type': 'Organization', name: 'Spectre AI' },
    publisher: { '@type': 'Organization', name: 'Spectre AI', url: BASE_URL },
    datePublished: article.publishedAt,
    dateModified: article.updatedAt,
    mainEntityOfPage: article.canonicalUrl,
    keywords: (article.tags || []).join(', '),
  };

  const filePath = path.join(dir, `${article.slug}.json`);
  fs.writeFileSync(filePath, JSON.stringify(article, null, 2), 'utf-8');
  invalidateCache(article.type);
  publishToDataApi(article);
  return article;
}

/**
 * Mirror a freshly-written article to the Spectre Data API.
 *
 * Disk is still the newsroom's source of truth, but this directory is
 * gitignored and production builds its bundle from COMMITTED files only - so
 * before this, nothing the desk wrote after the ignore rule landed ever
 * reached users (prod was serving 2026-06-11 content on 2026-07-29). The box
 * is now the live source; the bundle stays as the cold-start fallback.
 *
 * Deliberately fire-and-forget: publishing must never slow down or fail an
 * agent's write. A miss is self-healing - the next regeneration re-publishes
 * the same slug, and the endpoint upserts on (type, slug).
 */
function publishToDataApi(article) {
  const key = process.env.SPECTRE_API_KEY;
  if (!key || process.env.INTEL_PUBLISH_DISABLED === '1') return;
  const base = process.env.SPECTRE_API_BASE || 'http://204.168.244.18:3850';
  try {
    fetch(`${base}/v1/intel/articles`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-API-Key': key },
      body: JSON.stringify({ articles: [article] }),
      signal: AbortSignal.timeout(10000),
    }).catch((e) => console.warn(`[store] publish ${article.type}/${article.slug}:`, e.message));
  } catch (e) {
    console.warn('[store] publish failed:', e.message);
  }
}

/**
 * Load a single article by type and slug.
 */
function loadArticle(type, slug) {
  const filePath = path.join(ARTICLES_DIR, type, `${slug}.json`);
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    console.error(`[store] Failed to load ${type}/${slug}:`, e.message);
    return null;
  }
}

/**
 * List articles by type, sorted by publishedAt desc.
 * @param {string} type - Article type (daily, crypto, stocks, research, news)
 * @param {object} opts - { limit }
 */
function listArticles(type, opts = {}) {
  const dir = path.join(ARTICLES_DIR, type);
  if (!fs.existsSync(dir)) return [];
  const limit = opts.limit || 100;

  // Check cache first
  const cached = getCachedArticles(type);
  if (cached) return cached.slice(0, limit);

  try {
    const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
    const articles = files
      .map(f => {
        try {
          const data = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf-8'));
          return data;
        } catch (_) {
          return null;
        }
      })
      .filter(a => a && a.status === 'published')
      .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));

    setCachedArticles(type, articles);
    return articles.slice(0, limit);
  } catch (e) {
    console.error(`[store] Failed to list ${type}:`, e.message);
    return [];
  }
}

/**
 * `calendar` entries are DATA payloads wearing an article shape: the calendar
 * agent saves `content: JSON.stringify(data)` so /api/calendar can read the
 * outlook/themes/verdict back by slug (agents/calendarAnalysisAgent.js). Listing
 * them as articles renders a wall of JSON at the reader (prod shipped exactly
 * that on 2026-07-29). loadArticle()/listArticles() stay unfiltered — the
 * calendar routes read these by slug and by calendarType.
 * Mirror of isReadable() in apps/research/api/_lib/intelligence-store.js.
 */
function isReadable(a) {
  if (!a) return false;
  if (a.type === 'calendar' || a.calendarType) return false;
  return !/^\s*[[{]/.test(a.content || '');
}

/**
 * List all published articles across all types (reader surfaces: hub list,
 * sitemap, RSS — machine payloads excluded).
 */
function listAllPublished(opts = {}) {
  const limit = opts.limit || 200;
  const all = [];
  ['daily', 'crypto', 'stocks', 'research', 'news', 'calendar'].forEach(type => {
    all.push(...listArticles(type, { limit: 100 }).filter(isReadable));
  });
  all.sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));
  return all.slice(0, limit);
}

// ── NEWS-SPECIFIC QUERIES ──

/**
 * List news articles with optional filters.
 * Automatically filters out expired news (48h TTL).
 */
function listNews(opts = {}) {
  const { limit = 50, category, breakingOnly, featuredOnly } = opts;
  let articles = listArticles('news', { limit: 500 });

  // Filter expired articles (skip in dev so stale fixtures still render)
  if (process.env.NODE_ENV === 'production') {
    const now = Date.now();
    articles = articles.filter(a => !a.expiresAt || new Date(a.expiresAt).getTime() > now);
  }

  if (category && category !== 'all') {
    articles = articles.filter(a =>
      a.category === category ||
      (a.categories || []).includes(category)
    );
  }
  if (breakingOnly) articles = articles.filter(a => a.isBreaking);
  if (featuredOnly) articles = articles.filter(a => a.isFeatured);

  return articles.slice(0, limit);
}

/**
 * Get featured articles. Falls back to most recent if no featured exist.
 */
function getFeatured(limit = 5) {
  const featured = listNews({ limit: 20, featuredOnly: true });
  if (featured.length >= limit) return featured.slice(0, limit);

  // Backfill with recent non-featured articles
  const all = listAllPublished({ limit: 50 });
  const seen = new Set(featured.map(a => a.slug));
  const backfill = all.filter(a => !seen.has(a.slug)).slice(0, limit - featured.length);
  return [...featured, ...backfill].slice(0, limit);
}

/**
 * Get active breaking news (not expired, last 4 hours).
 */
function getBreaking() {
  const cutoff = new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString();
  const articles = listArticles('news', { limit: 10 });
  return articles.filter(a => a.isBreaking && a.publishedAt > cutoff);
}

/**
 * Get the most recent daily brief.
 */
function getLatestDailyBrief() {
  const briefs = listArticles('daily', { limit: 1 });
  return briefs[0] || null;
}

/**
 * Get stats about the content store.
 */
function getStats() {
  const counts = {};
  let total = 0;
  let lastGeneration = null;

  ['daily', 'crypto', 'stocks', 'research', 'news', 'calendar'].forEach(type => {
    const articles = listArticles(type, { limit: 1000 });
    counts[type] = articles.length;
    total += articles.length;
    if (articles.length > 0) {
      const latest = articles[0].updatedAt || articles[0].publishedAt;
      if (!lastGeneration || latest > lastGeneration) lastGeneration = latest;
    }
  });

  // Count today's articles
  const todayStr = new Date().toISOString().split('T')[0];
  const allArticles = listAllPublished({ limit: 1000 });
  const totalToday = allArticles.filter(a => (a.publishedAt || '').startsWith(todayStr)).length;

  // Category breakdown for news
  const newsArticles = listArticles('news', { limit: 1000 });
  const articlesByCategory = {};
  newsArticles.forEach(a => {
    const cat = a.category || 'general';
    articlesByCategory[cat] = (articlesByCategory[cat] || 0) + 1;
  });

  return {
    articlesPerDay: (counts.crypto || 0) + (counts.stocks || 0) + (counts.daily || 0) + (counts.news || 0),
    totalArticles: total,
    totalToday,
    lastGeneration: lastGeneration || null,
    agentsActive: true,
    coverage: counts,
    articlesByCategory,
  };
}

/**
 * Delete an article.
 */
function deleteArticle(type, slug) {
  const filePath = path.join(ARTICLES_DIR, type, `${slug}.json`);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    invalidateCache(type);
    return true;
  }
  return false;
}

module.exports = {
  saveArticle,
  loadArticle,
  listArticles,
  listAllPublished,
  listNews,
  getFeatured,
  getBreaking,
  getLatestDailyBrief,
  getStats,
  deleteArticle,
  ARTICLES_DIR,
  BASE_URL,
};
