/**
 * Vercel Serverless -- Intelligence Hub.
 * Reads from a build-time JSON bundle (apps/research/api/_data/intelligence-data.json)
 * generated by scripts/build-intelligence-content.mjs.
 *
 * Routing: vercel.json rewrites /api/intelligence/* to
 *   /api/intel-api?fn=intelligence-api&route=<sub-route>&<extra params>
 */
import {
  loadArticle,
  listArticles,
  listAllPublished,
  listNews,
  getFeatured,
  getBreaking,
  getLatestDailyBrief,
  getStats,
  summarize,
  summarizeNews,
  fetchLiveList,
  fetchLiveArticle,
} from '../intelligence-store.js'

const ALLOWED_ORIGINS = [
  'http://localhost:5180',
  'http://localhost:5181',
  'https://spectre-app-research.vercel.app',
  'https://spectre-trading.vercel.app',
]

function setCors(req, res) {
  res.setHeader(
    'Access-Control-Allow-Origin',
    ALLOWED_ORIGINS.includes(req.headers?.origin) ? req.headers.origin : ''
  )
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
}

export default async function handler(req, res) {
  setCors(req, res)
  if (req.method === 'OPTIONS') return res.status(200).end()

  const route = (req.query.route || '').toLowerCase()

  if (req.method === 'GET') {
    res.setHeader('Cache-Control', 'public, s-maxage=60, stale-while-revalidate=120')
  }

  // Base: GET /api/intelligence
  if (!route) {
    const limit = Math.min(parseInt(req.query.limit, 10) || 50, 200)
    // Live first, bundle as the cold-start fallback (see intelligence-store).
    const live = await fetchLiveList({ limit })
    if (live) return res.status(200).json({ count: live.length, articles: live, source: 'live' })
    const articles = listAllPublished({ limit })
    return res.status(200).json({
      count: articles.length,
      articles: articles.map(summarize),
    })
  }

  // GET /api/intelligence/breaking
  if (route === 'breaking') {
    const articles = getBreaking()
    return res.status(200).json({
      count: articles.length,
      articles: articles.map(summarizeNews),
    })
  }

  // GET /api/intelligence/news
  if (route === 'news') {
    const limit = Math.min(parseInt(req.query.limit, 10) || 15, 100)
    const category = req.query.category || undefined
    const breakingOnly = req.query.breaking === 'true'
    const featuredOnly = req.query.featured === 'true'
    const articles = listNews({ limit, category, breakingOnly, featuredOnly })
    return res.status(200).json({
      count: articles.length,
      articles: articles.map(summarizeNews),
    })
  }

  // GET /api/intelligence/featured
  if (route === 'featured') {
    const limit = Math.min(parseInt(req.query.limit, 10) || 5, 20)
    const articles = getFeatured(limit)
    return res.status(200).json({
      count: articles.length,
      articles: articles.map(summarizeNews),
    })
  }

  // GET /api/intelligence/activity — agent log not bundled, return empty.
  if (route === 'activity') {
    return res.status(200).json({ count: 0, events: [] })
  }

  // GET /api/intelligence/stats
  if (route === 'stats') {
    return res.status(200).json(getStats())
  }

  // GET /api/intelligence/:type/:slug
  if (route === 'article') {
    const { type, slug } = req.query
    if (!type || !slug) return res.status(400).json({ error: 'Missing type or slug' })
    const live = await fetchLiveArticle(String(type), String(slug))
    if (live) return res.status(200).json(live)
    const article = loadArticle(String(type), String(slug))
    if (!article) return res.status(404).json({ error: 'Article not found', type, slug })
    return res.status(200).json(article)
  }

  // GET /api/intelligence/:type
  if (route === 'type') {
    const { type } = req.query
    if (!type) return res.status(400).json({ error: 'Missing type' })
    const limit = Math.min(parseInt(req.query.limit, 10) || 50, 200)
    const live = await fetchLiveList({ types: [String(type)], limit })
    if (live) return res.status(200).json({ count: live.length, articles: live, source: 'live' })
    const articles = listArticles(String(type), { limit })
    return res.status(200).json({
      count: articles.length,
      articles: articles.map(summarize),
    })
  }

  // GET /api/intelligence/daily/latest
  if (route === 'daily-latest') {
    // The hub's masthead brief - the single most staleness-visible surface.
    const live = await fetchLiveList({ types: ['daily'], limit: 1 })
    if (live?.[0]?.slug) {
      const full = await fetchLiveArticle('daily', live[0].slug)
      if (full) return res.status(200).json(full)
    }
    const brief = getLatestDailyBrief()
    if (!brief) return res.status(404).json({ error: 'No daily brief found' })
    return res.status(200).json(brief)
  }

  return res.status(200).json({ count: 0, articles: [] })
}
