/**
 * Page Catalog — searchable index of every navigable surface in the research app.
 *
 * Powers the global search bar's "Pages" mode (Cmd-K style). Entries are matched
 * by title, aliases, and keywords with fuzzy scoring in `src/lib/pageSearchIndex.js`.
 *
 * Maintenance:
 *   - When a new <Route> is added to App.jsx, add a matching entry here.
 *   - Aliases should cover what users actually TYPE (typos, abbreviations, jargon).
 *   - Keywords should cover concepts the page touches (so "sentiment" finds Fear & Greed).
 *   - sub-tab entries use `tab=` query param and reference a `parent` page id.
 *
 * Field reference:
 *   id          — unique slug, kebab-case
 *   path        — exact router path (may include query params for sub-tabs)
 *   title       — display name shown in search results
 *   aliases     — alternate spellings, common typos, abbreviations (high match weight)
 *   description — one-line summary shown under the title in results
 *   keywords    — domain concepts; surfaces this page when user types related terms
 *   section     — top-level grouping for visual headers (Market | Discovery | AI | Tools | Social | Profile)
 *   parent      — id of parent page if this is a sub-tab
 *   iconHint    — name for icon lookup (resolved by the renderer)
 *   tier        — 1 = primary, 2 = secondary, 3 = utility (affects default ranking)
 */

export const PAGE_CATALOG = [
  // ── Home / Welcome ─────────────────────────────────────────────────────────
  {
    id: 'home',
    path: '/',
    title: 'Welcome',
    aliases: ['home', 'dashboard', 'main', 'landing', 'overview'],
    description: 'Daily market briefing, news, sectors, mindshare, calendar',
    keywords: ['home', 'today', 'morning', 'briefing'],
    section: 'Market',
    iconHint: 'home',
    tier: 1,
  },
  {
    id: 'home-brief',
    path: '/?tab=brief',
    title: 'Daily Brief',
    aliases: ['brief', 'ai brief', 'morning brief', 'daily'],
    description: 'Today\'s AI-generated market summary on the Welcome page',
    keywords: ['brief', 'morning', 'ai', 'summary', 'today'],
    section: 'Market',
    parent: 'home',
    iconHint: 'brief',
    tier: 1,
  },
  {
    id: 'home-news',
    path: '/?tab=news',
    title: 'News Feed (Welcome)',
    aliases: ['news', 'headlines', 'feed', 'crypto news'],
    description: 'Welcome page news tab — aggregated crypto news with sentiment',
    keywords: ['news', 'headlines', 'press', 'feed'],
    section: 'Market',
    parent: 'home',
    iconHint: 'news',
    tier: 2,
  },
  {
    id: 'home-liquidation',
    path: '/?tab=liquidation',
    title: 'Liquidation (Welcome)',
    aliases: ['liq', 'liquidations', 'rekt'],
    description: 'Liquidation heatmap tab on the Welcome page',
    keywords: ['liquidations', 'rekt', 'wipeout', 'cascade'],
    section: 'Market',
    parent: 'home',
    iconHint: 'liquidation',
    tier: 2,
  },
  {
    id: 'home-heatmap',
    path: '/?tab=heatmap',
    title: 'Heatmap (Welcome)',
    aliases: ['heatmap', 'treemap', 'market map'],
    description: 'Crypto market heatmap on the Welcome page',
    keywords: ['heatmap', 'treemap', 'colors', 'gainers', 'losers'],
    section: 'Market',
    parent: 'home',
    iconHint: 'heatmap',
    tier: 2,
  },
  {
    id: 'home-sectors',
    path: '/?tab=sectors',
    title: 'Sectors (Welcome)',
    aliases: ['sectors', 'sector rotation', 'categories'],
    description: 'Sector rotation view on the Welcome page',
    keywords: ['sectors', 'rotation', 'category', 'ai', 'defi', 'memes'],
    section: 'Market',
    parent: 'home',
    iconHint: 'sectors',
    tier: 2,
  },
  {
    id: 'home-mindshare',
    path: '/?tab=mindshare',
    title: 'Mindshare (Welcome)',
    aliases: ['mindshare', 'attention', 'social mindshare'],
    description: 'Social mindshare metrics on the Welcome page',
    keywords: ['mindshare', 'attention', 'social', 'twitter', 'x', 'narrative'],
    section: 'Market',
    parent: 'home',
    iconHint: 'mindshare',
    tier: 2,
  },
  {
    id: 'home-calendar',
    path: '/?tab=calendar',
    title: 'Calendar (Welcome)',
    aliases: ['calendar', 'economic calendar', 'events'],
    description: 'Economic calendar tab on the Welcome page',
    keywords: ['calendar', 'events', 'macro', 'fomc', 'cpi', 'unlock'],
    section: 'Market',
    parent: 'home',
    iconHint: 'calendar',
    tier: 2,
  },
  {
    id: 'home-flows',
    path: '/?tab=flows',
    title: 'Flows (Welcome)',
    aliases: ['flows', 'exchange flows', 'inflows', 'outflows'],
    description: 'Exchange flow data on the Welcome page',
    keywords: ['flows', 'exchange', 'inflow', 'outflow', 'cex'],
    section: 'Market',
    parent: 'home',
    iconHint: 'flows',
    tier: 2,
  },
  {
    id: 'home-wallets',
    path: '/?tab=wallets',
    title: 'Wallets (Welcome)',
    aliases: ['smart money', 'whales', 'wallet tracker'],
    description: 'Smart-money wallet activity tab on the Welcome page',
    keywords: ['smart money', 'whale', 'holdings', 'onchain'],
    section: 'Market',
    parent: 'home',
    iconHint: 'wallets',
    tier: 2,
  },
  {
    id: 'home-others',
    path: '/?tab=others',
    title: 'Alt Season / Others (Welcome)',
    aliases: ['others', 'others2', 'alt season', 'altseason', 'alt season gauge'],
    description: 'OTHERS chart + alt-season gauge tab on the Welcome page',
    keywords: ['others', 'alt season', 'altcoins', 'dominance', 'rotation', 'gauge'],
    section: 'Market',
    parent: 'home',
    iconHint: 'others',
    tier: 2,
  },

  // ── Market data ────────────────────────────────────────────────────────────
  {
    id: 'fear-greed',
    path: '/fear-greed',
    title: 'Fear & Greed',
    aliases: ['fng', 'fear and greed', 'sentiment index', 'fear greed', 'gauge'],
    description: 'Crypto Fear & Greed Index with 1Y history and component breakdown',
    keywords: ['sentiment', 'mood', 'index', 'gauge', 'market', 'extreme', 'panic'],
    section: 'Market',
    iconHint: 'fear-greed',
    tier: 1,
  },
  {
    id: 'heatmaps',
    path: '/heatmaps',
    title: 'Heatmaps',
    aliases: ['heatmap', 'treemap', 'market map', 'crypto heatmap'],
    description: 'Full crypto heatmaps + treemaps by market cap and 24h change',
    keywords: ['heatmap', 'treemap', 'gainers', 'losers', 'market map', 'visual'],
    section: 'Market',
    iconHint: 'heatmap',
    tier: 1,
  },
  {
    id: 'bubbles',
    path: '/bubbles',
    title: 'Bubble Map',
    aliases: ['bubbles', 'bubble chart', 'crypto bubbles'],
    description: 'Animated bubble chart of crypto tokens by market cap',
    keywords: ['bubbles', 'visualization', 'market cap', 'physics'],
    section: 'Market',
    iconHint: 'bubbles',
    tier: 2,
  },
  {
    id: 'alt-rotation',
    path: '/alt-rotation',
    title: 'Microcaps',
    aliases: [
      'microcaps', 'micro caps', 'micro-caps', 'alt rotation', 'altcoin rotation',
      'rotation', 'small caps', 'smallcaps', 'runners', 'low caps',
    ],
    description: 'Microcap & altcoin rotation board — where capital is rotating next',
    keywords: ['microcap', 'altcoin', 'rotation', 'small cap', 'runner', 'momentum', 'alt season'],
    section: 'Market',
    iconHint: 'rotation',
    tier: 1,
  },
  {
    id: 'why',
    path: '/why',
    title: 'Why',
    aliases: ['why mode', 'why is the market', 'market timeline', 'what happened', 'timeline'],
    description: 'Why the market moved — live thesis, 48h story, key events timeline',
    keywords: ['why', 'timeline', 'events', 'story', 'thesis', 'narrative', 'moved', 'dump', 'pump', 'fomc'],
    section: 'Market',
    iconHint: 'why',
    tier: 1,
  },
  {
    id: 'categories',
    path: '/categories',
    title: 'Categories',
    aliases: ['sectors', 'category', 'cg categories'],
    description: 'CoinGecko categories — AI, DeFi, RWA, memes, etc.',
    keywords: ['categories', 'sectors', 'ai', 'defi', 'memes', 'rwa', 'gaming'],
    section: 'Market',
    iconHint: 'categories',
    tier: 1,
  },
  {
    id: 'liquidation-heatmap',
    path: '/liquidation-heatmap',
    title: 'Liquidation Heatmap',
    aliases: ['liq heatmap', 'liquidations', 'rekt map', 'liq levels', 'liquidation map', 'liq map'],
    description: 'BTC/ETH liquidation levels heatmap, map view, depth and zones',
    keywords: ['liquidations', 'leverage', 'cascade', 'levels', 'btc', 'eth', 'derivatives', 'map'],
    section: 'Market',
    iconHint: 'liquidation',
    tier: 1,
  },
  {
    id: 'etf-flows',
    path: '/etfs',
    title: 'ETF Flows',
    aliases: [
      'etf', 'etfs', 'etf flows', 'net flows', 'bitcoin etf', 'btc etf',
      'eth etf', 'spot etf', 'ibit', 'issuers', 'blackrock', 'fidelity',
    ],
    description: 'Spot BTC/ETH ETF net flows, issuer table and premium/discount',
    keywords: ['etf', 'flows', 'institutional', 'blackrock', 'ibit', 'fidelity', 'grayscale', 'inflow', 'outflow'],
    section: 'Market',
    iconHint: 'etf',
    tier: 1,
  },
  {
    id: 'discover',
    path: '/discover',
    title: 'Discover',
    aliases: ['discovery', 'find tokens', 'explore'],
    description: 'Token discovery — trending, new listings, themes',
    keywords: ['discover', 'trending', 'new', 'explore', 'find'],
    section: 'Discovery',
    iconHint: 'discover',
    tier: 1,
  },
  {
    id: 'watchlists',
    path: '/watchlists',
    title: 'Watchlists',
    aliases: ['watchlist', 'my list', 'favorites', 'starred'],
    description: 'Your token watchlists with live prices, sparklines, analysis',
    keywords: ['watchlist', 'favorites', 'tracking', 'portfolio', 'my tokens'],
    section: 'Profile',
    iconHint: 'watchlists',
    tier: 1,
  },

  // ── Research / dossier ────────────────────────────────────────────────────
  {
    id: 'research-zone',
    path: '/research-zone',
    title: 'Research Zone',
    aliases: ['rz', 'research', 'deep dive', 'token research'],
    description: 'Deep-dive research view for any token — chart, technicals, sentiment, brain',
    keywords: ['research', 'deep dive', 'token', 'analysis', 'chart', 'thesis'],
    section: 'Discovery',
    iconHint: 'research',
    tier: 1,
  },
  {
    id: 'dossier',
    path: '/dossier',
    title: 'Dossier',
    aliases: ['profile', 'token dossier', 'project'],
    description: 'Project dossier — full token intelligence panel',
    keywords: ['dossier', 'profile', 'project', 'intelligence', 'team', 'backers'],
    section: 'Discovery',
    iconHint: 'dossier',
    tier: 1,
  },
  {
    id: 'token',
    path: '/trade',
    title: 'AI Screener',
    aliases: ['ai screener', 'screener', 'trading lite', 'trade', 'swap', 'token page', 'token'],
    description: 'AI Screener — token chart, screener + swap UI (embeds trading app)',
    keywords: ['screener', 'trade', 'swap', 'chart', 'buy', 'sell', 'execution', 'onchain'],
    section: 'Discovery',
    iconHint: 'trade',
    tier: 1,
  },
  {
    id: 'lite',
    path: '/lite',
    title: 'Spectre Lite',
    aliases: ['lite', 'spectre lite', 'lite mode', 'simple mode', 'light mode app'],
    description: 'Spectre Lite — the simplified all-in-one dashboard (markets, why, research, social)',
    keywords: ['lite', 'simple', 'dashboard', 'overview', 'beginner', 'mobile'],
    section: 'Discovery',
    iconHint: 'lite',
    tier: 1,
  },
  {
    id: 'brain',
    path: '/brain',
    title: 'Brain',
    aliases: ['ai brain', 'spectre brain', 'thought'],
    description: 'Spectre Brain — live AI thesis, observations, lessons',
    keywords: ['brain', 'ai', 'thesis', 'conviction', 'observations', 'thoughts'],
    section: 'AI',
    iconHint: 'brain',
    tier: 1,
  },
  {
    id: 'pulse',
    path: '/pulse',
    title: 'Pulse',
    aliases: ['live pulse', 'real-time', 'pulse feed'],
    description: 'Real-time market pulse — events as they happen',
    keywords: ['pulse', 'live', 'realtime', 'events', 'feed'],
    section: 'Market',
    iconHint: 'pulse',
    tier: 1,
  },
  {
    id: 'predictions',
    path: '/predictions',
    title: 'Predictions',
    aliases: [
      'prediction markets', 'polymarket', 'odds', 'kalshi', 'betting',
      'sports betting', 'election odds', 'fomc odds',
    ],
    description: 'Prediction markets — Polymarket + Kalshi events and odds',
    keywords: [
      'predictions', 'polymarket', 'kalshi', 'betting', 'odds', 'events',
      'yes no market', 'binary', 'wager',
    ],
    section: 'Market',
    iconHint: 'predictions',
    tier: 1,
  },
  {
    id: 'alerts',
    path: '/alerts',
    title: 'Alerts',
    aliases: ['notifications', 'alarms', 'price alerts'],
    description: 'Manage your price + signal alerts',
    keywords: ['alerts', 'notifications', 'alarms', 'triggers', 'price'],
    section: 'Profile',
    iconHint: 'alerts',
    tier: 1,
  },
  {
    id: 'intelligence-feed',
    path: '/insights',
    title: 'Intel Desk',
    // The old name stays an alias: it is what the row was called for months,
    // and it is still the bell popover's title.
    aliases: ['insights', 'intel feed', 'intelligence feed', 'signals', 'alerts feed', 'notifications'],
    description: 'Every signal the desk has raised — laned, searchable, kept',
    keywords: ['intel', 'desk', 'intelligence', 'insights', 'signals', 'lanes', 'alerts', 'notifications', 'breaking'],
    section: 'AI',
    iconHint: 'feed',
    tier: 1,
  },

  // ── AI / Charts / Content ─────────────────────────────────────────────────
  {
    id: 'ai-charts',
    path: '/ai-charts',
    title: 'AI Charts',
    aliases: ['ai chart', 'charts ai', 'ai analysis'],
    description: 'AI-annotated price charts with auto-detected patterns',
    keywords: ['ai', 'charts', 'patterns', 'analysis', 'technical'],
    section: 'AI',
    iconHint: 'charts',
    tier: 1,
  },
  {
    id: 'ai-market-analysis',
    path: '/ai-market-analysis',
    title: 'AI Market Analysis',
    aliases: ['market ai', 'ai market', 'macro ai'],
    description: 'AI-generated macro market analysis',
    keywords: ['ai', 'market', 'macro', 'analysis', 'thesis'],
    section: 'AI',
    iconHint: 'analysis',
    tier: 1,
  },
  {
    id: 'monarch-chat',
    path: '/monarch-chat',
    title: 'Monarch Chat',
    aliases: ['monarch', 'ai chat', 'chat'],
    description: 'Monarch — your AI research assistant',
    keywords: ['chat', 'ai', 'monarch', 'assistant', 'ask', 'question'],
    section: 'AI',
    iconHint: 'chat',
    tier: 1,
  },
  {
    id: 'intelligence',
    path: '/intelligence',
    title: 'Intelligence',
    aliases: ['research articles', 'intel hub', 'reports'],
    description: 'Spectre Intelligence — research articles, deep dives, market reports',
    keywords: ['intelligence', 'research', 'articles', 'reports', 'reading'],
    section: 'AI',
    iconHint: 'intelligence',
    tier: 1,
  },
  {
    id: 'ai-media-center',
    path: '/ai-media-center',
    title: 'AI Media Center',
    aliases: ['media', 'video', 'podcasts', 'spectre tv'],
    description: 'AI-generated podcasts + video briefings',
    keywords: ['media', 'video', 'audio', 'podcasts', 'tv'],
    section: 'AI',
    iconHint: 'media',
    tier: 2,
  },
  {
    id: 'newsroom',
    path: '/newsroom',
    title: 'Newsroom',
    aliases: ['news room', 'spectre press', 'editorial'],
    description: 'Spectre Newsroom — editorial articles',
    keywords: ['news', 'editorial', 'press', 'articles'],
    section: 'AI',
    iconHint: 'newsroom',
    tier: 2,
  },
  {
    id: 'news',
    path: '/news',
    title: 'News',
    aliases: ['headlines', 'crypto news', 'press'],
    description: 'Full crypto news feed with filtering and sentiment',
    keywords: ['news', 'headlines', 'press', 'feed'],
    section: 'Market',
    iconHint: 'news',
    tier: 1,
  },
  {
    id: 'lens',
    path: '/lens',
    title: 'Lens',
    aliases: ['ai lens', 'narrative lens'],
    description: 'Narrative + thematic lens — see the market through a single theme',
    keywords: ['lens', 'theme', 'narrative', 'angle'],
    section: 'AI',
    iconHint: 'lens',
    tier: 2,
  },

  // ── Social / X-Dash ───────────────────────────────────────────────────────
  {
    id: 'x-dash',
    path: '/x-dash',
    title: 'X-Dash',
    aliases: [
      'twitter dashboard', 'x dashboard', 'social leaderboard', 'attention',
      'momentum board', 'spectre momentum', 'signal score', 'velocity',
      'novelty', 'clean signal', 'mention spike',
    ],
    description: 'X (Twitter) attention leaderboard — momentum tokens by social signal, velocity, novelty',
    keywords: [
      'x', 'twitter', 'social', 'attention', 'mentions', 'leaderboard',
      'momentum', 'signal', 'velocity', 'novelty', 'tweets', 'cashtag',
    ],
    section: 'Social',
    iconHint: 'x-dash',
    tier: 1,
  },
  {
    id: 'x-dash-creators',
    path: '/x-dash/creators',
    title: 'X-Dash Creators',
    aliases: [
      'kol leaderboard', 'creators', 'influencers', 'kols', 'twitter kols',
      'crypto kols', 'top creators', 'verified accounts', 'shillers',
    ],
    description: 'Top KOLs ranked by aggregated attention they generate',
    keywords: [
      'kol', 'creators', 'influencers', 'twitter', 'x', 'verified',
      'shiller', 'promoter', 'commentator',
    ],
    section: 'Social',
    parent: 'x-dash',
    iconHint: 'kol',
    tier: 1,
  },
  {
    id: 'x-dash-kol-radar',
    path: '/x-dash/kol-radar',
    title: 'KOL Radar',
    aliases: ['kol radar', 'radar', 'follow kols', 'big guns', 'kol tracker', 'my kols'],
    description: 'Your followed KOLs — live calls, activity and track record',
    keywords: ['kol', 'radar', 'follow', 'tracker', 'calls', 'twitter', 'x'],
    section: 'Social',
    parent: 'x-dash',
    iconHint: 'kol',
    tier: 1,
  },
  {
    id: 'x-dash-new-tokens',
    path: '/x-dash',
    title: 'X-Dash New Tokens',
    aliases: ['new tokens', 'fresh tokens', 'newly indexed'],
    description: 'New tab on X-Dash — tokens newly indexed by the crawler',
    keywords: ['new', 'fresh', 'tokens', 'launch', 'newly indexed'],
    section: 'Social',
    parent: 'x-dash',
    iconHint: 'new',
    tier: 2,
  },
  {
    id: 'x-dash-rotations',
    path: '/x-dash/rotations',
    title: 'X-Dash Rotations',
    aliases: ['rotations', 'sector rotation x', 'kol rotation'],
    description: 'How KOLs are rotating attention between tokens',
    keywords: ['rotations', 'flow', 'kol movement'],
    section: 'Social',
    parent: 'x-dash',
    iconHint: 'rotation',
    tier: 2,
  },
  {
    id: 'x-dash-creator-edits',
    path: '/x-dash/creator-edits',
    title: 'X-Dash Creator Edits',
    aliases: ['creator edits', 'kol edits'],
    description: 'Manual edits to creator classifications',
    keywords: ['creator', 'edits', 'manual', 'classification'],
    section: 'Social',
    parent: 'x-dash',
    iconHint: 'edits',
    tier: 3,
  },
  {
    id: 'x-intelligence',
    path: '/x-intelligence',
    title: 'X Intelligence',
    aliases: ['x intel', 'social intel', 'mention chart'],
    description: 'Mention-time charts + social graph for any token',
    keywords: ['x', 'twitter', 'social', 'graph', 'mentions', 'chart'],
    section: 'Social',
    iconHint: 'x-intel',
    tier: 1,
  },
  {
    id: 'wallets',
    path: '/wallets',
    title: 'Wallets',
    aliases: ['wallet analysis', 'smart money', 'whale tracker', 'money flow', 'hyperliquid desks'],
    description: 'Smart-money flows, whale tape, CEX/ETF/stable flows and Hyperliquid smart-desk positioning',
    keywords: ['wallets', 'smart money', 'whales', 'flows', 'nansen', 'hyperliquid', 'etf'],
    section: 'Market',
    iconHint: 'wallets',
    tier: 1,
  },
  {
    id: 'x-intel',
    path: '/x-intel',
    title: 'X Intel (Legacy)',
    aliases: ['x intel legacy', 'old x intel'],
    description: 'Legacy X-Intel surface',
    keywords: ['x', 'intel', 'twitter'],
    section: 'Social',
    iconHint: 'x-intel',
    tier: 3,
  },
  {
    id: 'x-bubbles',
    path: '/x-bubbles',
    title: 'X Bubbles',
    aliases: ['bubble x', 'social bubbles'],
    description: 'Bubble visualization of X attention',
    keywords: ['bubbles', 'x', 'twitter', 'social', 'visualization'],
    section: 'Social',
    iconHint: 'bubbles',
    tier: 2,
  },
  {
    id: 'social-zone',
    path: '/social-zone',
    title: 'Social Zone',
    aliases: ['social', 'community'],
    description: 'Social aggregator — all social surfaces in one place',
    keywords: ['social', 'community', 'hub'],
    section: 'Social',
    iconHint: 'social',
    tier: 2,
  },
  {
    id: 'gm-dashboard',
    path: '/gm-dashboard',
    title: 'GM Dashboard',
    aliases: ['gm', 'good morning', 'morning dashboard'],
    description: 'Good Morning dashboard — start-of-day briefing layout',
    keywords: ['gm', 'morning', 'briefing', 'dashboard'],
    section: 'AI',
    iconHint: 'gm',
    tier: 2,
  },

  // ── Tokenized Assets / RWA ────────────────────────────────────────────────
  {
    id: 'tokenized-assets',
    path: '/tokenized-assets',
    title: 'Tokenized Assets',
    aliases: [
      'rwa', 'real world assets', 'rwas', 'tokenized', 'tokenization',
      'on-chain real world', 'tokenized rwa', 'rwa market',
      'issuer direct', 'asset class allocation',
    ],
    description: 'RWA dashboard — issuer-direct AUM, breakdowns, stablecoins, treasuries, commodities, equities',
    keywords: [
      'rwa', 'tokenized', 'real world', 'aum', 'issuers', 'treasuries',
      'buidl', 'ousg', 'usdy', 'benji', 'pax gold', 'xaut', 'commodities',
      'tokenized real estate', 'tokenized equity', 'centrifuge', 'maple',
    ],
    section: 'Market',
    iconHint: 'rwa',
    tier: 1,
  },
  {
    id: 'tokenized-overview',
    path: '/tokenized-assets?tab=overview',
    title: 'RWA Overview',
    aliases: ['rwa overview', 'rwa hero'],
    description: 'RWA market overview — total AUM, top issuers, chain breakdown',
    keywords: ['rwa', 'overview', 'aum', 'totals'],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'overview',
    tier: 2,
  },
  {
    id: 'tokenized-stablecoins',
    path: '/tokenized-assets?tab=stablecoins',
    title: 'Stablecoins',
    aliases: [
      'stables', 'usdc', 'usdt', 'usde', 'usdd', 'fdusd', 'rlusd', 'usdp',
      'stablecoin', 'tether', 'circle', 'ethena', 'paxos', 'pyusd', 'sky',
      'dai', 'frax', 'pegged',
    ],
    description: 'Stablecoin supply + issuer tracking (USDC, USDT, USDe, FDUSD, PYUSD, RLUSD)',
    keywords: [
      'stablecoins', 'stable', 'usdc', 'usdt', 'tether', 'circle', 'usde',
      'ethena', 'fdusd', 'rlusd', 'pyusd', 'dai', 'frax', 'paxos', 'pegged',
    ],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'stablecoins',
    tier: 1,
  },
  {
    id: 'tokenized-treasuries',
    path: '/tokenized-assets?tab=treasuries',
    title: 'Tokenized Treasuries',
    aliases: [
      'us treasury', 'treasuries', 'buidl', 'ousg', 'usdy', 'benji', 'usyc',
      'hashnote', 'blackrock', 'ondo', 'franklin', 'wisdomtree', 'wtsyx',
      'tokenized bonds', 'tokenized bills', 'tbill', 't-bill',
    ],
    description: 'Tokenized US Treasury products — BUIDL (BlackRock), OUSG/USDY (Ondo), BENJI (Franklin), USYC (Hashnote)',
    keywords: [
      'treasuries', 'treasury', 'us treasury', 'buidl', 'blackrock', 'ondo',
      'franklin', 'usdy', 'ousg', 'benji', 'usyc', 'hashnote', 'tbill',
      'bonds', 'yield', 'nav',
    ],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'treasury',
    tier: 1,
  },
  {
    id: 'tokenized-credit',
    path: '/tokenized-assets?tab=credit',
    title: 'Tokenized Credit',
    aliases: [
      'credit', 'private credit', 'maple', 'goldfinch', 'centrifuge',
      'clearpool', 'truefi', 'figure', 'tokenized lending', 'rwa lending',
    ],
    description: 'Tokenized private credit — Maple, Centrifuge, Goldfinch, Clearpool',
    keywords: [
      'credit', 'private credit', 'lending', 'maple', 'centrifuge',
      'goldfinch', 'clearpool', 'truefi', 'rwa lending',
    ],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'credit',
    tier: 1,
  },
  {
    id: 'tokenized-risk-alpha',
    path: '/tokenized-assets?tab=risk-alpha',
    title: 'RWA Risk / Alpha',
    aliases: ['rwa risk', 'rwa alpha', 'yield curve'],
    description: 'RWA yield curve, concentration, NAV watch',
    keywords: ['risk', 'alpha', 'yield', 'concentration', 'nav'],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'risk',
    tier: 2,
  },
  {
    id: 'tokenized-platforms',
    path: '/tokenized-assets?tab=platforms',
    title: 'RWA Platforms',
    aliases: ['rwa platforms', 'issuers list'],
    description: 'All RWA issuance platforms with TVL + adapter status',
    keywords: ['platforms', 'issuers', 'adapters'],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'platforms',
    tier: 2,
  },
  {
    id: 'tokenized-screener',
    path: '/tokenized-assets?tab=screener',
    title: 'RWA Screener',
    aliases: ['rwa screener', 'rwa filter'],
    description: 'Filter and rank RWA assets by yield, AUM, holders',
    keywords: ['screener', 'filter', 'rank', 'rwa'],
    section: 'Market',
    parent: 'tokenized-assets',
    iconHint: 'screener',
    tier: 2,
  },

  // ── Ventures / Private Markets ────────────────────────────────────────────
  {
    id: 'ventures',
    path: '/ventures',
    title: 'Ventures',
    aliases: [
      'vc', 'venture capital', 'private', 'institutional', 'institutional scores',
      'spectre score', 'grayscale', 'grayscale candidates', 'etf candidates',
      'tier list', 'project grades', 'a+ grade', 'discovery hot', 'discovery new',
      'yc', 'ycombinator', 'y combinator', 'techstars', 'accelerator',
      'accelerators', 'a16z', 'paradigm', 'sequoia', 'binance labs',
      'polychain', 'multicoin',
    ],
    description: 'Institutional scoring + venture-grade project tracking, accelerators (YC, Techstars), Grayscale/ETF/Coinbase signals',
    keywords: [
      'ventures', 'vc', 'institutional', 'grade', 'projects', 'scoring',
      'grayscale', 'etf', 'cme', 'coinbase', 'tier', 'rank', 'spectre score',
      'a+', 'institutional grade', 'discovery',
      'yc', 'ycombinator', 'techstars', 'accelerator', 'a16z', 'paradigm',
      'binance labs', 'polychain',
    ],
    section: 'Discovery',
    iconHint: 'ventures',
    tier: 1,
  },
  {
    id: 'ventures-accelerators',
    path: '/ventures?view=accelerators',
    title: 'Accelerator Pipeline (Ventures)',
    aliases: [
      'accelerators', 'accelerator pipeline', 'yc batch', 'yc companies',
      'techstars portfolio', 'binance labs portfolio', 'incubator',
    ],
    description: 'Ventures view of accelerator-backed crypto projects',
    keywords: [
      'accelerator', 'yc', 'ycombinator', 'techstars', 'binance labs',
      'incubator', 'pipeline', 'cohort', 'batch',
    ],
    section: 'Discovery',
    parent: 'ventures',
    iconHint: 'accelerator',
    tier: 2,
  },
  {
    id: 'private-markets-accelerators',
    path: '/private-markets?tab=accelerators',
    title: 'Accelerators (Private Markets)',
    aliases: [
      'accelerators feed', 'yc deals', 'yc batch', 'techstars deals',
      'accelerator deals', 'yc companies', 'incubator deals',
    ],
    description: 'Private Markets accelerator feed — YC, Techstars, demo days',
    keywords: [
      'accelerator', 'yc', 'ycombinator', 'techstars', 'demo day',
      'cohort', 'batch', 's24', 'w24', 'f24',
    ],
    section: 'Discovery',
    parent: 'private-markets',
    iconHint: 'accelerator',
    tier: 2,
  },
  {
    id: 'private-markets',
    path: '/private-markets',
    title: 'Private Markets',
    aliases: [
      'private', 'pre-ipo', 'funding rounds', 'deals', 'startups',
      'yc', 'ycombinator', 'y combinator', 'techstars', 'accelerator',
      'accelerators', 'unicorn', 'unicorns', 'cap table',
      'sec filings', 'sec', '10-k', 's-1', 'edgar',
    ],
    description: 'Private market deal flow, SEC filings, accelerators (YC, Techstars), unicorn tracker',
    keywords: [
      'private', 'deals', 'sec', 'edgar', 'funding', 'rounds', 'series',
      'yc', 'ycombinator', 'techstars', 'accelerator', 'unicorn', 'startup',
      'venture', 'preipo', 'cap table', 'fundraise', 'raise',
    ],
    section: 'Discovery',
    iconHint: 'private',
    tier: 1,
  },
  {
    id: 'potential-gainers',
    path: '/potential-gainers',
    title: 'Potential Gainers',
    aliases: ['gainers', 'momentum setups', 'movers'],
    description: 'Momentum board — tokens flagged as upside setups',
    keywords: ['gainers', 'momentum', 'setups', 'breakout', 'movers'],
    section: 'Discovery',
    iconHint: 'momentum',
    tier: 1,
  },
  {
    id: 'traders-corner',
    path: '/traders-corner',
    title: 'Traders Corner',
    aliases: [
      'tc', 'trader', 'derivatives', 'futures', 'perpetuals', 'perps',
      'funding rate', 'open interest', 'cvd', 'order book', 'orderbook',
      'liquidation bubbles', 'liq bubbles', 'liq timeline', 'depth chart',
      'cot', 'commitment of traders', 'long short ratio', 'lsr',
    ],
    description: 'Pro derivatives desk — OI, funding rate, CVD, order book depth, liquidations',
    keywords: [
      'traders', 'derivatives', 'futures', 'perp', 'perpetual', 'funding',
      'oi', 'open interest', 'cvd', 'order book', 'depth', 'liquidation',
      'binance futures', 'bybit', 'okx', 'deribit',
    ],
    section: 'Discovery',
    iconHint: 'traders',
    tier: 1,
  },

  // ── Ecosystem hubs ────────────────────────────────────────────────────────
  {
    id: 'zigchain',
    path: '/zigchain',
    title: 'ZIGChain',
    aliases: ['zig', 'zigchain hub', 'zignaly'],
    description: 'ZIGChain ecosystem hub — price, TVL, founders, episodes',
    keywords: ['zigchain', 'zig', 'zignaly', 'ecosystem'],
    section: 'Discovery',
    iconHint: 'zigchain',
    tier: 1,
  },

  // ── Tools ─────────────────────────────────────────────────────────────────
  {
    id: 'economic-calendar',
    path: '/economic-calendar',
    title: 'Economic Calendar',
    aliases: [
      'calendar', 'macro', 'fomc', 'cpi', 'nfp', 'ppi', 'gdp', 'pce',
      'events', 'fed meeting', 'fed', 'jerome powell', 'rate decision',
      'jobs report', 'unemployment', 'unlock', 'token unlock', 'unlocks',
      'earnings calendar',
    ],
    description: 'Macro economic calendar — Fed, CPI, NFP, PPI, GDP, token unlocks, earnings',
    keywords: [
      'calendar', 'fed', 'fomc', 'cpi', 'nfp', 'ppi', 'pce', 'gdp',
      'macro', 'unlocks', 'unlock', 'earnings', 'powell', 'rate hike',
    ],
    section: 'Tools',
    iconHint: 'calendar',
    tier: 1,
  },
  {
    id: 'roi-calculator',
    path: '/roi-calculator',
    title: 'ROI Calculator',
    aliases: ['roi', 'calculator', 'profit calc'],
    description: 'Calculate ROI on hypothetical entries + exits',
    keywords: ['roi', 'calculator', 'profit', 'return', 'gains'],
    section: 'Tools',
    iconHint: 'calculator',
    tier: 2,
  },
  {
    id: 'search-engine',
    path: '/search-engine',
    title: 'Search Engine',
    aliases: ['search', 'spectre search', 'token search'],
    description: 'Spectre token search engine',
    keywords: ['search', 'find', 'token', 'lookup'],
    section: 'Tools',
    iconHint: 'search',
    tier: 2,
  },
  {
    id: 'world',
    path: '/world',
    title: 'World',
    aliases: ['globe', '3d world', 'world view'],
    description: '3D globe view of crypto activity worldwide',
    keywords: ['world', 'globe', '3d', 'geography', 'visualization'],
    section: 'Tools',
    iconHint: 'world',
    tier: 2,
  },
  {
    id: 'structure-guide',
    path: '/structure-guide',
    title: 'App Map',
    aliases: ['structure', 'guide', 'site map', 'app map'],
    description: 'Internal structure guide — see every page and where it lives',
    keywords: ['structure', 'guide', 'sitemap', 'pages', 'help'],
    section: 'Tools',
    iconHint: 'guide',
    tier: 3,
  },

  // ── Profile / Account ─────────────────────────────────────────────────────
  {
    id: 'you',
    path: '/you',
    title: 'You',
    aliases: ['profile', 'account', 'me', 'my profile'],
    description: 'Your Spectre profile — portfolio, history, studio',
    keywords: ['you', 'profile', 'account', 'me', 'my'],
    section: 'Profile',
    iconHint: 'you',
    tier: 1,
  },
  {
    id: 'user-dashboard',
    path: '/user-dashboard',
    title: 'Dashboard',
    aliases: ['my dashboard', 'user dashboard', 'home'],
    description: 'Personal dashboard with portfolio + watchlists summary',
    keywords: ['dashboard', 'portfolio', 'profile'],
    section: 'Profile',
    iconHint: 'dashboard',
    tier: 1,
  },

  // ── Landing / Public ──────────────────────────────────────────────────────
  {
    id: 'website2',
    path: '/website2',
    title: 'Spectre Website',
    aliases: ['landing', 'home page', 'website'],
    description: 'Public landing page',
    keywords: ['landing', 'website', 'marketing', 'home'],
    section: 'Tools',
    iconHint: 'website',
    tier: 3,
  },
  {
    id: 'website2-api',
    path: '/website2/api',
    title: 'API Documentation',
    aliases: ['api docs', 'developers', 'api'],
    description: 'Public API documentation for developers',
    keywords: ['api', 'docs', 'developers', 'integration'],
    section: 'Tools',
    iconHint: 'api',
    tier: 3,
  },
  {
    id: 'website2-api-dashboard',
    path: '/website2/api/dashboard',
    title: 'API Dashboard',
    aliases: ['api dashboard', 'developer dashboard', 'api keys'],
    description: 'Developer API dashboard — manage keys, usage, billing',
    keywords: ['api', 'dashboard', 'keys', 'developer'],
    section: 'Tools',
    iconHint: 'api',
    tier: 3,
  },
  {
    id: 'facts',
    path: '/facts',
    title: 'Facts',
    aliases: ['facts page', 'about facts'],
    description: 'Spectre facts page',
    keywords: ['facts', 'about'],
    section: 'Tools',
    iconHint: 'facts',
    tier: 3,
  },
  {
    id: 'arena',
    path: '/arena',
    title: 'Agent Arena',
    aliases: ['arena', 'paper traders', 'trading agents', 'strategy leaderboard'],
    description: 'The paper-trading strategies as a public scoreboard — equity curves, drawdowns, every close reason, losers included',
    keywords: ['arena', 'agents', 'paper trading', 'strategies', 'leaderboard', 'equity', 'brain'],
    section: 'AI',
    iconHint: 'arena',
    tier: 1,
  },
  {
    id: 'market-cinema',
    path: '/cinema',
    title: 'Market Cinema',
    aliases: ['cinema', 'ambient market', 'liquidation rain', 'whale flows'],
    description: 'Full-screen ambient market stage — live liquidations, labeled whale and stablecoin flows',
    keywords: ['cinema', 'liquidations', 'whales', 'stablecoin', 'ambient', 'live', 'flows'],
    section: 'Market',
    iconHint: 'cinema',
    tier: 1,
  },
  {
    id: 'world-state',
    path: '/world-state',
    title: 'World State',
    aliases: ['macro state', 'world doc', 'fed odds', 'net liquidity', 'macro consciousness'],
    description: 'The versioned macro-politics document — Fed odds, net liquidity tide, COT positioning, policy stances with quotes',
    keywords: ['macro', 'fed', 'fomc', 'liquidity', 'cot', 'politics', 'regime', 'world state'],
    section: 'AI',
    iconHint: 'world-state',
    tier: 1,
  },
  {
    id: 'vitals',
    path: '/vitals',
    title: 'Vitals',
    aliases: ['platform fundamentals', 'protocol revenue', 'fees and revenue', 'user growth', 'defi fundamentals'],
    description: 'Revenue, fees, users, volume and TVL for every platform — with per-app active traders and trader PnL measured first-hand',
    keywords: ['revenue', 'fees', 'fundamentals', 'users', 'dau', 'tvl', 'take rate', 'growth', 'leaderboard', 'protocol', 'platform'],
    section: 'Market',
    iconHint: 'vitals',
    tier: 1,
  },
]

/**
 * Quick lookup by id (for navigation hints, recent pages).
 */
export const PAGE_CATALOG_BY_ID = PAGE_CATALOG.reduce((acc, e) => {
  acc[e.id] = e
  return acc
}, {})

/**
 * Entries grouped by section, for rendering grouped result lists.
 */
export const SECTION_ORDER = ['Market', 'Discovery', 'AI', 'Social', 'Tools', 'Profile']
